import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/ui/styles/globals.css";
import "@/ui/styles/utilities.css";
import "@/ui/styles/colors.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="app">{children}</div>
      </body>
    </html>
  );
}
