import type { Metadata } from "next";
import "@/lib/ui/styles/globals.css";
import "@/lib/ui/styles/utilities.css";
import "@/lib/ui/styles/colors.css";
import StoreProvider from "./appConfigs/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

const RootLayout = ({ children }: Props) => {
  return (
    <html lang="en">
      <body>
        <div className="app">
          <StoreProvider>{children}</StoreProvider>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
